// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lmsProject.Models;

namespace lmsProject.Migrations
{
    [DbContext(typeof(lmsContext))]
    [Migration("20191210110346_Add AnhPath")]
    partial class AddAnhPath
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lmsProject.Models.Dattruoc", b =>
                {
                    b.Property<string>("Mathe")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Masach")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool>("Danhan");

                    b.Property<DateTime>("Ngaydattruoc")
                        .HasColumnType("date");

                    b.HasKey("Mathe", "Masach");

                    b.HasIndex("Masach");

                    b.ToTable("Dattruoc");
                });

            modelBuilder.Entity("lmsProject.Models.Luotmuon", b =>
                {
                    b.Property<string>("Mathe")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Masach")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime>("Ngayhethan")
                        .HasColumnType("date");

                    b.Property<DateTime>("Ngaymuon")
                        .HasColumnType("date");

                    b.Property<DateTime>("Ngaytra")
                        .HasColumnType("date");

                    b.Property<double>("Tienphat");

                    b.Property<bool>("Tinhtrangsachluctra");

                    b.HasKey("Mathe", "Masach");

                    b.HasIndex("Masach");

                    b.ToTable("Luotmuon");
                });

            modelBuilder.Entity("lmsProject.Models.Nhomsach", b =>
                {
                    b.Property<string>("Manhomsach")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("AnhPath");

                    b.Property<double>("Giatien");

                    b.Property<string>("Magiasach")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Matheloai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("Soluong");

                    b.Property<int>("Soluongcon");

                    b.Property<string>("Tacgia");

                    b.Property<string>("Tensach")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Manhomsach");

                    b.HasIndex("Matheloai");

                    b.ToTable("Nhomsach");
                });

            modelBuilder.Entity("lmsProject.Models.Phieumuon", b =>
                {
                    b.Property<string>("Mathe")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Masach")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool>("Datra");

                    b.Property<bool>("Giahan");

                    b.Property<DateTime>("Ngayhethan")
                        .HasColumnType("date");

                    b.Property<DateTime>("Ngaymuon")
                        .HasColumnType("date");

                    b.HasKey("Mathe", "Masach");

                    b.HasIndex("Masach");

                    b.ToTable("Phieumuon");
                });

            modelBuilder.Entity("lmsProject.Models.Sach", b =>
                {
                    b.Property<string>("Masach")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool>("Damuon");

                    b.Property<string>("Manhomsach")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<bool>("Tinhtrangsach");

                    b.HasKey("Masach");

                    b.HasIndex("Manhomsach");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("lmsProject.Models.Theloai", b =>
                {
                    b.Property<string>("Matheloai")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("Songaymuontoida");

                    b.Property<string>("Tentheloai")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Matheloai");

                    b.ToTable("Theloai");
                });

            modelBuilder.Entity("lmsProject.Models.User", b =>
                {
                    b.Property<string>("Mathe")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Diachi")
                        .HasMaxLength(100);

                    b.Property<bool?>("Gioitinh");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("Ngaydangki")
                        .HasColumnType("date");

                    b.Property<DateTime>("Ngayhethan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("date");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Role")
                        .IsRequired();

                    b.Property<int>("Sosachdamuon");

                    b.HasKey("Mathe");

                    b.ToTable("User");
                });

            modelBuilder.Entity("lmsProject.Models.Dattruoc", b =>
                {
                    b.HasOne("lmsProject.Models.Sach", "MasachNavigation")
                        .WithMany("Dattruoc")
                        .HasForeignKey("Masach")
                        .HasConstraintName("FK_Dattruoc_Sach")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("lmsProject.Models.User", "MatheNavigation")
                        .WithMany("Dattruoc")
                        .HasForeignKey("Mathe")
                        .HasConstraintName("FK_Dattruoc_User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("lmsProject.Models.Luotmuon", b =>
                {
                    b.HasOne("lmsProject.Models.Sach", "MasachNavigation")
                        .WithMany("Luotmuon")
                        .HasForeignKey("Masach")
                        .HasConstraintName("FK_Luotmuon_Sach")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("lmsProject.Models.User", "MatheNavigation")
                        .WithMany("Luotmuon")
                        .HasForeignKey("Mathe")
                        .HasConstraintName("FK_Luotmuon_User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("lmsProject.Models.Nhomsach", b =>
                {
                    b.HasOne("lmsProject.Models.Theloai", "MatheloaiNavigation")
                        .WithMany("Nhomsach")
                        .HasForeignKey("Matheloai")
                        .HasConstraintName("FK_Nhomsach_Theloai")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("lmsProject.Models.Phieumuon", b =>
                {
                    b.HasOne("lmsProject.Models.Sach", "MasachNavigation")
                        .WithMany("Phieumuon")
                        .HasForeignKey("Masach")
                        .HasConstraintName("FK_Phieumuon_Sach")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("lmsProject.Models.User", "MatheNavigation")
                        .WithMany("Phieumuon")
                        .HasForeignKey("Mathe")
                        .HasConstraintName("FK_Phieumuon_User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("lmsProject.Models.Sach", b =>
                {
                    b.HasOne("lmsProject.Models.Nhomsach", "ManhomsachNavigation")
                        .WithMany("Sach")
                        .HasForeignKey("Manhomsach")
                        .HasConstraintName("FK_Sach_Nhomsach");
                });
#pragma warning restore 612, 618
        }
    }
}
